CREATE TABLE talent (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   first_name VARCHAR(20) NOT NULL,
   last_name VARCHAR(20) NOT NULL,
   specialization VARCHAR(30) NOT NULL,
   image VARCHAR(100),
   CONSTRAINT pk_talent PRIMARY KEY (id)
);

create TABLE talent_description (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   talent_id BIGINT NOT NULL,
   BIO VARCHAR(255) NOT NULL,
   addition_info VARCHAR(255) NOT NULL,
   CONSTRAINT pk_talent_description PRIMARY KEY (id)
);

alter table talent_description add CONSTRAINT FK_TALENT_DESCRIPTION_ON_TALENT FOREIGN KEY (talent_id) REFERENCES talent (id);

create TABLE talent_link (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   talent_id BIGINT NOT NULL,
   link VARCHAR(255) NOT NULL,
   CONSTRAINT pk_talent_link PRIMARY KEY (id)
);

alter table talent_link add CONSTRAINT FK_TALENT_LINK_ON_TALENT FOREIGN KEY (talent_id) REFERENCES talent (id);

create TABLE talent_skill (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   talent_id BIGINT NOT NULL,
   skill VARCHAR(255) NOT NULL,
   CONSTRAINT pk_talent_skill PRIMARY KEY (id)
);

alter table talent_skill add CONSTRAINT FK_TALENT_SKILL_ON_TALENT FOREIGN KEY (talent_id) REFERENCES talent (id);

create TABLE talent_contact (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   talent_id BIGINT NOT NULL,
   contact VARCHAR(255) NOT NULL,
   CONSTRAINT pk_talent_contact PRIMARY KEY (id)
);

alter table talent_contact add CONSTRAINT FK_TALENT_CONTACT_ON_TALENT FOREIGN KEY (talent_id) REFERENCES talent (id);

create TABLE talent_attached_file (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   talent_id BIGINT NOT NULL,
   attached_file VARCHAR(100) NOT NULL,
   CONSTRAINT pk_talent_attached_file PRIMARY KEY (id)
);

alter table talent_attached_file add CONSTRAINT FK_TALENT_ATTACHED_FILE_ON_TALENT FOREIGN KEY (talent_id) REFERENCES talent (id);

