CREATE TABLE deleted_user
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    time_to_delete    TIMESTAMP WITHOUT TIME ZONE,
    uuid_for_activate VARCHAR(255),
    CONSTRAINT pk_deleted_user PRIMARY KEY (id)
);

ALTER TABLE deleted_user
    ADD CONSTRAINT FK_DELETED_USER_ON_ID FOREIGN KEY (id) REFERENCES users_info (id);